name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: add Debian Packages
      if: matrix.os == 'ubuntu-latest'
      uses: myci-actions/add-deb-repo@10
      with:
        repo-name: obs
        repo: deb http://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-draft/xUbuntu_20.04/ ./
        keys-asc: https://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-draft/xUbuntu_20.04/Release.key
        install: libzmq5 libzmq3-dev libglx-dev mesa-common-dev libasound2-dev libglew-dev libunwind-dev

    - name: Add brew packages
      if: matrix.os == 'macos-latest'
      shell: bash
      run: brew install automake autoconf cmake

    - name: libZMQ Dep
      if: matrix.os == 'macos-latest'
      run: |
        git clone https://github.com/zeromq/libzmq.git
        cd libzmq
        ./autogen.sh
        ./configure
        make
        sudo make install

    - name: Python dep
      if: matrix.os == 'macos-latest'
      run: |
        ./dist/osx/build_python.sh ${{github.workspace}}/build/python
        export CMAKE_OPTIONS="-DPython3_ROOT_DIR=${{github.workspace}}/build/python -DWITH_EMBED_PYTHON=ON"

    - name: Submodule Checkout
      run: git submodule update --init --recursive

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} $CMAKE_OPTIONS

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}} -VV

    - name: Upload file via SSH
      uses: nicklasfrahm/scp-action@main
      with:
        direction: upload
        host: ${{ secrets.SSH_TARGET_HOST }}
        fingerprint: ${{ secrets.SSH_TARGET_FINGERPRINT }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: |
          path/to/source/a.txt
          path/to/source/b.txt
        target: path/to/target
